### ISSUE TITLE
glowyphp or atomastic?

### ISSUE THREAD

**Issue by Kristories** [glowyphp/website#1]
Which is the correct name?

- https://digital.flextype.org/glowyphp (404)
- [**array**](https://github.com/glowyphp/array) : [404](https://digital.flextype.org/glowyphp/packages/arrays)
- [**string**](https://github.com/glowyphp/strings) : [404](https://digital.flextype.org/glowyphp/packages/strings)
- Other..

**Comment by Awilum** [comment]
Hello @Kristories Atomastic was rebranded to Glowy PHP Packages (glowy/[package_name])
Website will be updated for Glowy PHP Packages until end of this year.

**Comment by Kristories** [comment]
Oh noted! Is it still open for contributions at this time?

**Comment by Awilum** [comment]
If your question is about packages, yes you may contribute to any of open packages: https://github.com/glowyphp more packages will published in 2022.

If your question is about website, than I would answer, a lot of uncomited code I have for a new website on my local laptop and will push this code upcoming days.

**Comment by Kristories** [comment]
Yes for components. I'm just worried it will interfere. Thank you!
